// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: docs/proto/v1/download.proto

// Имя пакета

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealtheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *string                `protobuf:"bytes,1,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealtheckResponse) Reset() {
	*x = HealtheckResponse{}
	mi := &file_docs_proto_v1_download_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealtheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealtheckResponse) ProtoMessage() {}

func (x *HealtheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_download_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealtheckResponse.ProtoReflect.Descriptor instead.
func (*HealtheckResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_download_proto_rawDescGZIP(), []int{0}
}

func (x *HealtheckResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         []*Task                `protobuf:"bytes,1,rep,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_docs_proto_v1_download_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_download_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_download_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryResponse) GetQueue() []*Task {
	if x != nil {
		return x.Queue
	}
	return nil
}

type OnWork struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Link           string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Filename       string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	MoveTo         string                 `protobuf:"bytes,3,opt,name=moveTo,proto3" json:"moveTo,omitempty"`
	TargetQuantity int64                  `protobuf:"varint,4,opt,name=targetQuantity,proto3" json:"targetQuantity,omitempty"`
	Procentage     float64                `protobuf:"fixed64,5,opt,name=procentage,proto3" json:"procentage,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CurrentSize    float64                `protobuf:"fixed64,7,opt,name=currentSize,proto3" json:"currentSize,omitempty"`
	TotalSize      float64                `protobuf:"fixed64,8,opt,name=totalSize,proto3" json:"totalSize,omitempty"`
	Message        string                 `protobuf:"bytes,9,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OnWork) Reset() {
	*x = OnWork{}
	mi := &file_docs_proto_v1_download_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnWork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnWork) ProtoMessage() {}

func (x *OnWork) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_download_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnWork.ProtoReflect.Descriptor instead.
func (*OnWork) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_download_proto_rawDescGZIP(), []int{2}
}

func (x *OnWork) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *OnWork) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *OnWork) GetMoveTo() string {
	if x != nil {
		return x.MoveTo
	}
	return ""
}

func (x *OnWork) GetTargetQuantity() int64 {
	if x != nil {
		return x.TargetQuantity
	}
	return 0
}

func (x *OnWork) GetProcentage() float64 {
	if x != nil {
		return x.Procentage
	}
	return 0
}

func (x *OnWork) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OnWork) GetCurrentSize() float64 {
	if x != nil {
		return x.CurrentSize
	}
	return 0
}

func (x *OnWork) GetTotalSize() float64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *OnWork) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinksInWork   []*OnWork              `protobuf:"bytes,1,rep,name=linksInWork,proto3" json:"linksInWork,omitempty"`
	Sensors       string                 `protobuf:"bytes,2,opt,name=sensors,proto3" json:"sensors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_docs_proto_v1_download_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_download_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_download_proto_rawDescGZIP(), []int{3}
}

func (x *StatusResponse) GetLinksInWork() []*OnWork {
	if x != nil {
		return x.LinksInWork
	}
	return nil
}

func (x *StatusResponse) GetSensors() string {
	if x != nil {
		return x.Sensors
	}
	return ""
}

type CleanHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	History       []*Task                `protobuf:"bytes,1,rep,name=history,proto3" json:"history,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanHistoryResponse) Reset() {
	*x = CleanHistoryResponse{}
	mi := &file_docs_proto_v1_download_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanHistoryResponse) ProtoMessage() {}

func (x *CleanHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_download_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanHistoryResponse.ProtoReflect.Descriptor instead.
func (*CleanHistoryResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_download_proto_rawDescGZIP(), []int{4}
}

func (x *CleanHistoryResponse) GetHistory() []*Task {
	if x != nil {
		return x.History
	}
	return nil
}

type DeleteFromQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFromQueueRequest) Reset() {
	*x = DeleteFromQueueRequest{}
	mi := &file_docs_proto_v1_download_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFromQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFromQueueRequest) ProtoMessage() {}

func (x *DeleteFromQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_download_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFromQueueRequest.ProtoReflect.Descriptor instead.
func (*DeleteFromQueueRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_download_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteFromQueueRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

type DeleteFromQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinksInWork   []*Task                `protobuf:"bytes,1,rep,name=linksInWork,proto3" json:"linksInWork,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFromQueueResponse) Reset() {
	*x = DeleteFromQueueResponse{}
	mi := &file_docs_proto_v1_download_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFromQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFromQueueResponse) ProtoMessage() {}

func (x *DeleteFromQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_download_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFromQueueResponse.ProtoReflect.Descriptor instead.
func (*DeleteFromQueueResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_download_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteFromQueueResponse) GetLinksInWork() []*Task {
	if x != nil {
		return x.LinksInWork
	}
	return nil
}

type SetToQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	MaxQuality    *int32                 `protobuf:"varint,2,opt,name=maxQuality,proto3,oneof" json:"maxQuality,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetToQueueRequest) Reset() {
	*x = SetToQueueRequest{}
	mi := &file_docs_proto_v1_download_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetToQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetToQueueRequest) ProtoMessage() {}

func (x *SetToQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_download_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetToQueueRequest.ProtoReflect.Descriptor instead.
func (*SetToQueueRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_download_proto_rawDescGZIP(), []int{7}
}

func (x *SetToQueueRequest) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *SetToQueueRequest) GetMaxQuality() int32 {
	if x != nil && x.MaxQuality != nil {
		return *x.MaxQuality
	}
	return 0
}

type SetToQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinksInWork   []*Task                `protobuf:"bytes,1,rep,name=linksInWork,proto3" json:"linksInWork,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetToQueueResponse) Reset() {
	*x = SetToQueueResponse{}
	mi := &file_docs_proto_v1_download_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetToQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetToQueueResponse) ProtoMessage() {}

func (x *SetToQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_download_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetToQueueResponse.ProtoReflect.Descriptor instead.
func (*SetToQueueResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_download_proto_rawDescGZIP(), []int{8}
}

func (x *SetToQueueResponse) GetLinksInWork() []*Task {
	if x != nil {
		return x.LinksInWork
	}
	return nil
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          string                 `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	MaxQuantity   string                 `protobuf:"bytes,3,opt,name=maxQuantity,proto3" json:"maxQuantity,omitempty"`
	Name          *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Message       *string                `protobuf:"bytes,5,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_docs_proto_v1_download_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_download_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_download_proto_rawDescGZIP(), []int{9}
}

func (x *Task) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetMaxQuantity() string {
	if x != nil {
		return x.MaxQuantity
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Task) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_docs_proto_v1_download_proto protoreflect.FileDescriptor

const file_docs_proto_v1_download_proto_rawDesc = "" +
	"\n" +
	"\x1cdocs/proto/v1/download.proto\x12\agrpc.v1\x1a\x1bgoogle/protobuf/empty.proto\">\n" +
	"\x11HealtheckResponse\x12\x1d\n" +
	"\amessage\x18\x01 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message\"6\n" +
	"\x0fHistoryResponse\x12#\n" +
	"\x05queue\x18\x01 \x03(\v2\r.grpc.v1.TaskR\x05queue\"\x8a\x02\n" +
	"\x06OnWork\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x16\n" +
	"\x06moveTo\x18\x03 \x01(\tR\x06moveTo\x12&\n" +
	"\x0etargetQuantity\x18\x04 \x01(\x03R\x0etargetQuantity\x12\x1e\n" +
	"\n" +
	"procentage\x18\x05 \x01(\x01R\n" +
	"procentage\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12 \n" +
	"\vcurrentSize\x18\a \x01(\x01R\vcurrentSize\x12\x1c\n" +
	"\ttotalSize\x18\b \x01(\x01R\ttotalSize\x12\x18\n" +
	"\amessage\x18\t \x01(\tR\amessage\"]\n" +
	"\x0eStatusResponse\x121\n" +
	"\vlinksInWork\x18\x01 \x03(\v2\x0f.grpc.v1.OnWorkR\vlinksInWork\x12\x18\n" +
	"\asensors\x18\x02 \x01(\tR\asensors\"?\n" +
	"\x14CleanHistoryResponse\x12'\n" +
	"\ahistory\x18\x01 \x03(\v2\r.grpc.v1.TaskR\ahistory\",\n" +
	"\x16DeleteFromQueueRequest\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\"J\n" +
	"\x17DeleteFromQueueResponse\x12/\n" +
	"\vlinksInWork\x18\x01 \x03(\v2\r.grpc.v1.TaskR\vlinksInWork\"[\n" +
	"\x11SetToQueueRequest\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12#\n" +
	"\n" +
	"maxQuality\x18\x02 \x01(\x05H\x00R\n" +
	"maxQuality\x88\x01\x01B\r\n" +
	"\v_maxQuality\"E\n" +
	"\x12SetToQueueResponse\x12/\n" +
	"\vlinksInWork\x18\x01 \x03(\v2\r.grpc.v1.TaskR\vlinksInWork\"\xa1\x01\n" +
	"\x04Task\x12\x12\n" +
	"\x04link\x18\x01 \x01(\tR\x04link\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12 \n" +
	"\vmaxQuantity\x18\x03 \x01(\tR\vmaxQuantity\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\amessage\x18\x05 \x01(\tH\x01R\amessage\x88\x01\x01B\a\n" +
	"\x05_nameB\n" +
	"\n" +
	"\b_message2\xb3\x03\n" +
	"\n" +
	"Downloader\x12G\n" +
	"\n" +
	"SetToQueue\x12\x1a.grpc.v1.SetToQueueRequest\x1a\x1b.grpc.v1.SetToQueueResponse\"\x00\x12V\n" +
	"\x0fDeleteFromQueue\x12\x1f.grpc.v1.DeleteFromQueueRequest\x1a .grpc.v1.DeleteFromQueueResponse\"\x00\x12G\n" +
	"\fCleanHistory\x12\x16.google.protobuf.Empty\x1a\x1d.grpc.v1.CleanHistoryResponse\"\x00\x12;\n" +
	"\x06Status\x12\x16.google.protobuf.Empty\x1a\x17.grpc.v1.StatusResponse\"\x00\x12;\n" +
	"\x05Queue\x12\x16.google.protobuf.Empty\x1a\x18.grpc.v1.HistoryResponse\"\x00\x12A\n" +
	"\tHealtheck\x12\x16.google.protobuf.Empty\x1a\x1a.grpc.v1.HealtheckResponse\"\x00B\x0fZ\rdocs/proto/v1b\x06proto3"

var (
	file_docs_proto_v1_download_proto_rawDescOnce sync.Once
	file_docs_proto_v1_download_proto_rawDescData []byte
)

func file_docs_proto_v1_download_proto_rawDescGZIP() []byte {
	file_docs_proto_v1_download_proto_rawDescOnce.Do(func() {
		file_docs_proto_v1_download_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_proto_v1_download_proto_rawDesc), len(file_docs_proto_v1_download_proto_rawDesc)))
	})
	return file_docs_proto_v1_download_proto_rawDescData
}

var file_docs_proto_v1_download_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_docs_proto_v1_download_proto_goTypes = []any{
	(*HealtheckResponse)(nil),       // 0: grpc.v1.HealtheckResponse
	(*HistoryResponse)(nil),         // 1: grpc.v1.HistoryResponse
	(*OnWork)(nil),                  // 2: grpc.v1.OnWork
	(*StatusResponse)(nil),          // 3: grpc.v1.StatusResponse
	(*CleanHistoryResponse)(nil),    // 4: grpc.v1.CleanHistoryResponse
	(*DeleteFromQueueRequest)(nil),  // 5: grpc.v1.DeleteFromQueueRequest
	(*DeleteFromQueueResponse)(nil), // 6: grpc.v1.DeleteFromQueueResponse
	(*SetToQueueRequest)(nil),       // 7: grpc.v1.SetToQueueRequest
	(*SetToQueueResponse)(nil),      // 8: grpc.v1.SetToQueueResponse
	(*Task)(nil),                    // 9: grpc.v1.Task
	(*emptypb.Empty)(nil),           // 10: google.protobuf.Empty
}
var file_docs_proto_v1_download_proto_depIdxs = []int32{
	9,  // 0: grpc.v1.HistoryResponse.queue:type_name -> grpc.v1.Task
	2,  // 1: grpc.v1.StatusResponse.linksInWork:type_name -> grpc.v1.OnWork
	9,  // 2: grpc.v1.CleanHistoryResponse.history:type_name -> grpc.v1.Task
	9,  // 3: grpc.v1.DeleteFromQueueResponse.linksInWork:type_name -> grpc.v1.Task
	9,  // 4: grpc.v1.SetToQueueResponse.linksInWork:type_name -> grpc.v1.Task
	7,  // 5: grpc.v1.Downloader.SetToQueue:input_type -> grpc.v1.SetToQueueRequest
	5,  // 6: grpc.v1.Downloader.DeleteFromQueue:input_type -> grpc.v1.DeleteFromQueueRequest
	10, // 7: grpc.v1.Downloader.CleanHistory:input_type -> google.protobuf.Empty
	10, // 8: grpc.v1.Downloader.Status:input_type -> google.protobuf.Empty
	10, // 9: grpc.v1.Downloader.Queue:input_type -> google.protobuf.Empty
	10, // 10: grpc.v1.Downloader.Healtheck:input_type -> google.protobuf.Empty
	8,  // 11: grpc.v1.Downloader.SetToQueue:output_type -> grpc.v1.SetToQueueResponse
	6,  // 12: grpc.v1.Downloader.DeleteFromQueue:output_type -> grpc.v1.DeleteFromQueueResponse
	4,  // 13: grpc.v1.Downloader.CleanHistory:output_type -> grpc.v1.CleanHistoryResponse
	3,  // 14: grpc.v1.Downloader.Status:output_type -> grpc.v1.StatusResponse
	1,  // 15: grpc.v1.Downloader.Queue:output_type -> grpc.v1.HistoryResponse
	0,  // 16: grpc.v1.Downloader.Healtheck:output_type -> grpc.v1.HealtheckResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_docs_proto_v1_download_proto_init() }
func file_docs_proto_v1_download_proto_init() {
	if File_docs_proto_v1_download_proto != nil {
		return
	}
	file_docs_proto_v1_download_proto_msgTypes[0].OneofWrappers = []any{}
	file_docs_proto_v1_download_proto_msgTypes[7].OneofWrappers = []any{}
	file_docs_proto_v1_download_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_v1_download_proto_rawDesc), len(file_docs_proto_v1_download_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_v1_download_proto_goTypes,
		DependencyIndexes: file_docs_proto_v1_download_proto_depIdxs,
		MessageInfos:      file_docs_proto_v1_download_proto_msgTypes,
	}.Build()
	File_docs_proto_v1_download_proto = out.File
	file_docs_proto_v1_download_proto_goTypes = nil
	file_docs_proto_v1_download_proto_depIdxs = nil
}
