// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: docs/proto/v1/download.proto

// Имя пакета

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_docs_proto_v1_download_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_download_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_download_proto_rawDescGZIP(), []int{0}
}

type DownloadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_docs_proto_v1_download_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_docs_proto_v1_download_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_docs_proto_v1_download_proto_rawDescGZIP(), []int{1}
}

var File_docs_proto_v1_download_proto protoreflect.FileDescriptor

const file_docs_proto_v1_download_proto_rawDesc = "" +
	"\n" +
	"\x1cdocs/proto/v1/download.proto\x12\agrpc.v1\"\x11\n" +
	"\x0fDownloadRequest\"\x12\n" +
	"\x10DownloadResponse2O\n" +
	"\n" +
	"Downloader\x12A\n" +
	"\bDownload\x12\x18.grpc.v1.DownloadRequest\x1a\x19.grpc.v1.DownloadResponse\"\x00B\x0fZ\rdocs/proto/v1b\x06proto3"

var (
	file_docs_proto_v1_download_proto_rawDescOnce sync.Once
	file_docs_proto_v1_download_proto_rawDescData []byte
)

func file_docs_proto_v1_download_proto_rawDescGZIP() []byte {
	file_docs_proto_v1_download_proto_rawDescOnce.Do(func() {
		file_docs_proto_v1_download_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_docs_proto_v1_download_proto_rawDesc), len(file_docs_proto_v1_download_proto_rawDesc)))
	})
	return file_docs_proto_v1_download_proto_rawDescData
}

var file_docs_proto_v1_download_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_docs_proto_v1_download_proto_goTypes = []any{
	(*DownloadRequest)(nil),  // 0: grpc.v1.DownloadRequest
	(*DownloadResponse)(nil), // 1: grpc.v1.DownloadResponse
}
var file_docs_proto_v1_download_proto_depIdxs = []int32{
	0, // 0: grpc.v1.Downloader.Download:input_type -> grpc.v1.DownloadRequest
	1, // 1: grpc.v1.Downloader.Download:output_type -> grpc.v1.DownloadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_docs_proto_v1_download_proto_init() }
func file_docs_proto_v1_download_proto_init() {
	if File_docs_proto_v1_download_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_docs_proto_v1_download_proto_rawDesc), len(file_docs_proto_v1_download_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_docs_proto_v1_download_proto_goTypes,
		DependencyIndexes: file_docs_proto_v1_download_proto_depIdxs,
		MessageInfos:      file_docs_proto_v1_download_proto_msgTypes,
	}.Build()
	File_docs_proto_v1_download_proto = out.File
	file_docs_proto_v1_download_proto_goTypes = nil
	file_docs_proto_v1_download_proto_depIdxs = nil
}
